# Site settings
title: Jian Jin
email: jinjian.pku@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life is an exciting journey.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jianPKU
github_username:  jianjinucdavis

# Build settings
markdown: kramdown
